
// TargetDir:   D:\Dropbox\[work] projects\T4Generator\T4Generator\T4Templates\bin\Debug\
// TargetPath:  D:\Dropbox\[work] projects\T4Generator\T4Generator\T4Templates\bin\Debug\T4Templates.dll
// SolutionDir: D:\Dropbox\[work] projects\T4Generator\T4Generator\

   


// autogenerated

using System;
using System.Collections.Generic;

namespace Interfaces
{
    public interface ISampleClientGenerated
    {
        List<int> GetUserAlertTemplates(SampleClassLibrary.UserContextContract userContext);
        List<string> GetSomethingMagic(int integerValue);
    }
}


