using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

using CodeGeneration;

using SampleClassLibrary;

namespace ConsoleApplication
{
    class Program
    {
        static void Main(string[] args)
        {
            //var generatedCode = Generator.GenerateClientClass<SampleController>();
            var generatedCode = Generator.GenerateInterface<SampleController>();
            Console.WriteLine(generatedCode);
            Console.ReadKey();

            // todo: generate body for http.post
            // todo: correctly process [FromUri]
            // todo: compare with existing methods 

            // todo: attribute [WithAutoGeneratedInterface]
        }
    }
}
